# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinPyQt5.9-32bit-3.5.3.1\testPyQt5\test01\exp03.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 275)
        self.hint11 = QtWidgets.QLabel(Form)
        self.hint11.setGeometry(QtCore.QRect(180, 160, 131, 21))
        self.hint11.setText("")
        self.hint11.setObjectName("hint11")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-70, -100, 651, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logo/注册.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 130, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 210, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(62, 204, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 210, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(62, 204, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(280, 60, 121, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 90, 121, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 130, 121, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.hint = QtWidgets.QLabel(Form)
        self.hint.setGeometry(QtCore.QRect(210, 170, 141, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.hint.setFont(font)
        self.hint.setText("")
        self.hint.setObjectName("hint")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "register"))
        self.label_2.setText(_translate("Form", "user"))
        self.label_4.setText(_translate("Form", "password"))
        self.label_5.setText(_translate("Form", "confirm password"))
        self.pushButton.setText(_translate("Form", "YES"))
        self.pushButton_2.setText(_translate("Form", "NO"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_signup()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
